- name: Install Nginx
  docker:
    name: nginx
    image: nginx
    detach: True
    ports:
        - 8080:8080
    expose:
        - 8080
    volumes:
        - /etc/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro